import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/navbar/main-nav";
import getUser from "@/actions/get-user";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { TProvider } from "@/components/toast-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUser();

  return (
    <html lang="en">
      <body className={inter.className}>
        <TProvider />
        <ThemeProvider attribute="class">
          <Navbar user={user} />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
